name: test
on: push
jobs:
  do_all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: sudo apt update &&
             sudo apt upgrade &&
             sudo apt install git cmake ninja
