name: test
on: push
jobs:
  do_all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: cat /sys/devices/system/cpu/cpu0/cache/index0/level &&
             cat /sys/devices/system/cpu/cpu0/cache/index0/type &&
             cat /sys/devices/system/cpu/cpu0/cache/index0/size &&
             cat /sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size &&
             cat /sys/devices/system/cpu/cpu0/cache/index0/ways_of_associativity
      - run: sudo apt install git cmake ninja &&
             mkdir -p build &&
             cd build &&
             cmake .. -GNinja &&
             ninja &&
             DEBUG_DUMP ./measure
